default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/yggdrasil_development

test:
  <<: *default
  database: db/yggdrasil_test

production:
  <<: *default
  database: db/yggdrasil_production
